// fix-all.mjs — one-command repair: files + database + password + start app
import { appendFileSync, existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { dirname, join } from 'node:path';

const step = (n, msg) => console.log('\n[' + n + '/7] ' + msg);
const ok = (msg) => console.log('      OK    ' + msg);
const warn = (msg) => console.log('      WARN  ' + msg);
const fail = (msg) => console.log('      FAIL  ' + msg);

if (typeof fetch === 'undefined') {
  fail('Your Node.js is too old. Install Node 18+ from nodejs.org, then run this again.');
  process.exit(1);
}

console.log('=== Fellowship Attendance — one-command setup & repair ===');

/* ---------------- 1. .env ---------------- */
step(1, 'Checking .env');
if (!existsSync('.env')) {
  fail('.env not found. Create it: copy .env.example to .env, add your Supabase URL + anon key, run again.');
  process.exit(1);
}
const env = {};
for (const line of readFileSync('.env', 'utf8').split('\n')) {
  const m = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$/);
  if (m) env[m[1]] = m[2].trim().replace(/^['"]|['"]$/g, '');
}
const URL_ = env.VITE_SUPABASE_URL;
const KEY_ = env.VITE_SUPABASE_ANON_KEY;
if (!URL_ || URL_.includes('your-project-ref')) { fail('VITE_SUPABASE_URL missing/placeholder in .env'); process.exit(1); }
if (!KEY_ || KEY_.includes('your-anon')) { fail('VITE_SUPABASE_ANON_KEY missing/placeholder in .env'); process.exit(1); }
ok('Supabase URL + anon key found');

let generatedPw = null;
if (!env.VITE_ADMIN_PASSWORD) {
  generatedPw = randomBytes(12).toString('base64url');
  appendFileSync('.env', '\n# Admin dashboard password (generated by fix-all)\nVITE_ADMIN_PASSWORD=' + generatedPw + '\n');
  ok('Generated a strong admin password and saved it into .env');
} else {
  ok('Admin password already configured in .env');
}

/* ---------------- 2. Dependencies ---------------- */
step(2, 'Checking dependencies');
if (!existsSync('node_modules')) {
  console.log('      Installing packages (this can take 1-2 minutes)...');
  const r = spawnSync('npm', ['install'], { stdio: 'inherit', shell: true });
  if (r.status !== 0) { fail('npm install failed'); process.exit(1); }
}
ok('node_modules present');

/* ---------------- 3. App files ---------------- */
step(3, 'Building/updating app files');
for (const script of ['create-project.mjs', 'update-project.mjs', 'update-dashboard.mjs']) {
  if (existsSync(script)) {
    const r = spawnSync(process.execPath, [script], { stdio: 'inherit' });
    if (r.status === 0) ok(script + ' applied');
    else fail(script + ' crashed — the file was likely pasted incomplete. Recreate it, then re-run.');
  } else {
    warn(script + ' not found — skipped');
  }
}

/* Admin sign-in screen with strong password (always written fresh) */
const ADMIN_GATE = `
import { Lock, UserRound } from 'lucide-react';
import { useState } from 'react';
import { Outlet } from 'react-router-dom';

const STORAGE_KEY = 'fa_admin_unlocked_v2';
const ADMIN_PASSWORD = import.meta.env.VITE_ADMIN_PASSWORD || '';

export function lockAdmin() {
  localStorage.removeItem(STORAGE_KEY);
}

export default function AdminGate() {
  const [unlocked, setUnlocked] = useState(() => localStorage.getItem(STORAGE_KEY) === '1');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');

  function handleSubmit(e) {
    e.preventDefault();
    if (!ADMIN_PASSWORD) return;
    if (password === ADMIN_PASSWORD) {
      localStorage.setItem(STORAGE_KEY, '1');
      setUnlocked(true);
    } else {
      setError('Incorrect password. Only fellowship admins can access this dashboard.');
      setPassword('');
    }
  }

  if (unlocked) return <Outlet />;

  return (
    <div className="flex min-h-screen items-center justify-center bg-white px-4">
      <form onSubmit={handleSubmit} className="card w-full max-w-sm p-8 text-center">
        <div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-brand-100 text-brand-700">
          <UserRound className="h-8 w-8" />
        </div>
        <h1 className="mt-4 text-xl font-bold text-red-700">Admin sign in</h1>
        {ADMIN_PASSWORD ? (
          <>
            <p className="mt-1 text-sm text-stone-500">
              This dashboard is reserved for fellowship admins. Enter the admin password.
            </p>
            <input
              type="password"
              autoFocus
              autoComplete="off"
              className="input mt-6"
              placeholder="Admin password"
              value={password}
              onChange={(e) => { setPassword(e.target.value); setError(''); }}
            />
            {error && <p className="mt-2 text-sm text-red-600" role="alert">{error}</p>}
            <button type="submit" className="btn-primary mt-5 w-full py-3">
              <Lock className="h-4 w-4" /> Sign in
            </button>
          </>
        ) : (
          <p className="mt-3 text-sm text-red-600">
            No admin password configured. Run: node fix-all.mjs
          </p>
        )}
        <p className="mt-4 text-xs text-stone-400">
          Not an admin? Use the QR code at the entrance to check in.
        </p>
      </form>
    </div>
  );
}
`;
const gatePath = join(process.cwd(), 'src/components/AdminGate.jsx');
mkdirSync(dirname(gatePath), { recursive: true });
writeFileSync(gatePath, ADMIN_GATE.startsWith('\n') ? ADMIN_GATE.slice(1) : ADMIN_GATE);
ok('AdminGate.jsx written (user sign-in + strong password)');

/* ---------------- 4. Verify files ---------------- */
step(4, 'Verifying app files');
const required = [
  'package.json', 'index.html', 'vite.config.js', 'tailwind.config.js', 'postcss.config.js',
  'src/main.jsx', 'src/App.jsx', 'src/index.css', 'src/lib/supabase.js',
  'src/components/AdminGate.jsx', 'src/components/Layout.jsx', 'src/components/RosterCard.jsx',
  'src/components/StatCard.jsx', 'src/components/PageHeader.jsx',
  'src/pages/DashboardPage.jsx', 'src/pages/CheckInPage.jsx', 'src/pages/KioskPage.jsx',
  'src/pages/AnalyticsPage.jsx', 'src/pages/MembersPage.jsx', 'src/pages/AttendancePage.jsx',
  'src/services/attendanceService.js', 'src/services/membersService.js', 'src/services/statsService.js',
  'src/hooks/useCheckIn.js', 'src/hooks/useStats.js', 'src/hooks/useDebounce.js',
];
const missing = required.filter((f) => !existsSync(f));
if (missing.length === 0) ok('All core files present (' + required.length + ')');
else { fail('Missing: ' + missing.join(', ') + '  — recreate the generator scripts and re-run.'); }

/* ---------------- 5. Supabase: probe ---------------- */
step(5, 'Connecting to Supabase');
async function sb(path, options = {}) {
  return fetch(URL_ + '/rest/v1/' + path, {
    ...options,
    headers: { apikey: KEY_, Authorization: 'Bearer ' + KEY_, ...(options.headers || {}) },
  });
}
function totalOf(res) {
  const cr = res.headers.get('content-range');
  if (!cr) return null;
  const n = cr.split('/')[1];
  return n && n !== '*' ? Number(n) : null;
}

let memberCount = 0;
let todayCount = 0;
let supabaseReady = false;

try {
  const probe = await sb('members?select=id', { headers: { Prefer: 'count=exact', Range: '0-0' } });
  if (probe.status === 401 || probe.status === 403) {
    warn('Supabase rejected the anon key. Check VITE_SUPABASE_ANON_KEY in .env.');
  } else if (!probe.ok) {
    warn('The "members" table does not exist in your database yet.');
    console.log('\n      The terminal cannot create tables. Do this ONE manual step:');
    console.log('      1. Supabase Dashboard -> SQL Editor -> New query');
    console.log('      2. Paste the ENTIRE supabase/schema.sql -> click Run');
    console.log('      3. Come back and run: node fix-all.mjs  (again)\n');
  } else {
    memberCount = totalOf(probe) ?? 0;
    supabaseReady = true;
    ok('Connected. members table found (' + memberCount + ' rows)');
  }
} catch (error) {
  warn('Supabase is unavailable right now: ' + (error?.message || String(error)));
  warn('Continuing in demo/offline mode so the app can still start.');
}

/* ---------------- 6. Supabase: seed ---------------- */
step(6, 'Checking & seeding data');

if (!supabaseReady) {
  warn('Skipping Supabase seeding because the service is unavailable or not configured yet.');
  console.log('\n      DATABASE STATUS: members = 0, today\'s check-ins = 0  (expected 50 / 30)');
} else {
  const NAMES = [
    ['Adaeze Okonkwo', 'Computer Science', 92], ['Bolanle Adebayo', 'Law', 90],
    ['Chukwuemeka Eze', 'Engineering', 88], ['Damilare Ogunleye', null, 85],
    ['Eseoghene Efe', 'Medicine', 83], ['Fatima Abdullahi', 'Accounting', 80],
    ['Gabriel Oladele', 'Computer Science', 78], ['Hadiza Mohammed', 'Law', 76],
    ['Ikenna Nwachukwu', 'Engineering', 74], ['Jumoke Balogun', 'Mass Communication', 71],
    ['Kelechi Okeke', 'Computer Science', 69], ['Lolade Ajayi', null, 67],
    ['Miriam Danjuma', 'Biochemistry', 65], ['Nnamdi Uzoma', 'Engineering', 62],
    ['Omolara Adeyemi', 'Law', 60], ['Peter Anyanwu', 'Computer Science', 58],
    ['Queensley Egbuna', 'Medicine', 55], ['Rasheedat Lawal', 'Accounting', 53],
    ['Samuel Adekunle', 'Engineering', 51], ['Titiola Bakare', 'Mass Communication', 49],
    ['Uche Nwankwo', 'Computer Science', 46], ['Vanessa Igwe', 'Law', 44],
    ['Wale Fashola', null, 42], ['Xaveria Okoro', 'Medicine', 40],
    ['Yusuf Garba', 'Engineering', 38], ['Zainab Suleiman', 'Accounting', 36],
    ['Abiodun Olatunji', 'Computer Science', 33], ['Chioma Agu', 'Law', 31],
    ['David Okon', 'Engineering', 29], ['Efe Esiri', 'Biochemistry', 27],
    ['Funmilayo Ransome', 'Medicine', 25], ['Godwin Obi', 'Computer Science', 23],
    ['Hauwa Bello', 'Law', 21], ['Ibrahim Danladi', 'Engineering', 19],
    ['Joy Ekpo', 'Accounting', 17], ['Kunle Awosika', 'Computer Science', 15],
    ['Love Okafor', 'Mass Communication', 13], ['Maryam Yusuf', 'Medicine', 11],
    ['Ndubisi Kanu', null, 9], ['Oluwaseun Ade', 'Engineering', 8],
    ['Patience Effiong', 'Law', 7], ['Quadri Ayinde', 'Computer Science', 6],
    ['Rebecca Mba', 'Accounting', 5], ['Solomon Tar', 'Engineering', 4],
    ['Tara Nwosu', 'Biochemistry', 3], ['Udo Bassey', 'Law', 2],
    ['Vivian Chukwu', 'Medicine', 1], ['Yakubu Musa', 'Computer Science', 1],
    ['Yetunde Alao', 'Mass Communication', 0.125], ['Zion Eze', 'Engineering', 0.083],
  ];
  const idFor = (n) => 'f47ac10b-58cc-4372-a567-0e02b2c3d4' + n.toString(16).padStart(2, '0');

  if (memberCount < 50) {
    const members = NAMES.map(([name, course, days], i) => ({
      id: idFor(i + 1),
      name,
      phone: '+234803111' + String(i + 1).padStart(4, '0'),
      email: name.toLowerCase().split(' ').join('.') + '@example.com',
      course,
      created_at: new Date(Date.now() - days * 86400000).toISOString(),
    }));
    const r = await sb('members', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Prefer: 'resolution=ignore-duplicates,return=minimal' },
      body: JSON.stringify(members),
    });
    if (r.ok) ok('Inserted members (duplicates skipped)');
    else { fail('Member insert failed: ' + (await r.text())); }
  } else {
    ok('Members already seeded (' + memberCount + ')');
  }

  function localDateStr(daysAgo) {
    const d = new Date(Date.now() - daysAgo * 86400000);
    const local = new Date(d.getTime() - d.getTimezoneOffset() * 60000);
    return local.toISOString().slice(0, 10);
  }
  const todayStr = localDateStr(0);
  const todayCheck = await sb('attendance?select=id&attendance_date=eq.' + todayStr, {
    headers: { Prefer: 'count=exact', Range: '0-0' },
  });
  todayCount = totalOf(todayCheck) ?? 0;

  if (todayCount < 30) {
    const MEETINGS = [
      { ago: 0, mins: 3, who: [1,2,3,5,6,8,9,11,12,14,15,17,19,20,22,23,25,26,28,30,31,33,35,36,38,40,42,44,47,50] },
      { ago: 3, mins: 4, who: [1,3,4,6,7,9,10,12,14,16,18,19,21,23,24,26,28,29,31,33,34,37,39,42,45,48] },
      { ago: 7, mins: 2, who: [1,2,3,4,5,7,8,10,11,12,13,15,16,18,20,21,22,24,25,26,27,29,30,32,34,35,37,38,40,41,43,44,46,48,49] },
      { ago: 10, mins: 4, who: [2,4,5,7,9,11,13,15,17,19,22,24,26,27,30,32,33,36,38,41,43,45,47,50] },
      { ago: 14, mins: 3, who: [1,2,4,5,6,8,9,10,12,13,14,16,17,19,21,23,24,25,27,28,30,31,33,35,36,38,39,41,43,45,46,48,50] },
    ];
    const rows = [];
    for (const mt of MEETINGS) {
      const dateStr = localDateStr(mt.ago);
      mt.who.forEach((num, idx) => {
        const t = new Date(dateStr + 'T09:00:00');
        t.setMinutes(t.getMinutes() + idx * mt.mins);
        rows.push({ member_id: idFor(num), attendance_date: dateStr, check_in_time: t.toISOString() });
      });
    }
    const r = await sb('attendance', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Prefer: 'resolution=ignore-duplicates,return=minimal' },
      body: JSON.stringify(rows),
    });
    if (r.ok) ok('Inserted attendance for 5 meetings (duplicates skipped)');
    else { fail('Attendance insert failed: ' + (await r.text())); }
  } else {
    ok("Today's attendance already present");
  }

  const finalMembers = totalOf(await sb('members?select=id', { headers: { Prefer: 'count=exact', Range: '0-0' } })) ?? '?';
  const finalToday = totalOf(await sb('attendance?select=id&attendance_date=eq.' + todayStr, { headers: { Prefer: 'count=exact', Range: '0-0' } })) ?? '?';
  console.log('\n      DATABASE STATUS: members = ' + finalMembers + ", today's check-ins = " + finalToday + '  (expected 50 / 30)');
}

/* ---------------- 7. Start ---------------- */
step(7, 'Starting the app');
console.log('\n==============================================================');
if (generatedPw) {
  console.log('   ADMIN PASSWORD (save it now — shown only once here):');
  console.log('   >>>  ' + generatedPw + '  <<<');
} else {
  console.log('   Admin password: the VITE_ADMIN_PASSWORD value inside your .env file');
}
console.log('==============================================================');
console.log('   Opening dev server. Then in your browser:');
console.log('   1. Go to  http://localhost:5173/dashboard');
console.log('   2. You will see the USER SIGN IN screen (Admin sign in)');
console.log('   3. Enter the password above');
console.log('   4. If the page looks old: Ctrl + Shift + R (hard refresh)');
console.log('   (Stop the server anytime with Ctrl + C)\n');

const dev = spawnSync('npm', ['run', 'dev'], { stdio: 'inherit', shell: true });
if (dev.status !== 0) fail('Dev server exited with an error — read the message above it.');